# Generated by Django 2.1.5 on 2019-01-21 04:25

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='cases.Tagulous_Case_tags', verbose_name='Case Tags'),
        ),
    ]
