# Generated by Django 2.1.7 on 2019-02-26 03:38

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190122_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='cases.Tagulous_Case_tags', verbose_name='Case Tags', verbose_name_plural='Case Tags'),
        ),
    ]
