# Generated by Django 2.1.7 on 2019-02-26 06:39

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190226_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='cases.Tagulous_Case_tags', verbose_name='Tags', verbose_name_plural='Tags'),
        ),
    ]
