# Generated by Django 2.1.7 on 2019-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20190226_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.IntegerField(choices=[(1, '最低'), (2, '低'), (3, '普通'), (4, '高'), (5, '最高')], default=3, verbose_name='Case Priority'),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='priority',
            field=models.IntegerField(choices=[(1, '最低'), (2, '低'), (3, '普通'), (4, '高'), (5, '最高')], default=3, verbose_name='Case Priority'),
        ),
    ]
