# Generated by Django 2.1.5 on 2019-01-21 11:16

import apps.files.storages
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.files.storages.PrivateStorage(bucket='froggy-service-case'), upload_to='', verbose_name='Case File')),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='File Name')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='Upload Time')),
            ],
            options={
                'verbose_name': 'Case File',
                'verbose_name_plural': 'Case File',
            },
        ),
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('case_uuid', models.UUIDField(verbose_name='UUID')),
                ('file', models.FileField(storage=apps.files.storages.PrivateStorage(bucket='froggy-service-temp'), upload_to='', verbose_name='Temp file')),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='File Name')),
                ('size', models.PositiveIntegerField(editable=False, verbose_name='Size')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='Upload Time')),
            ],
            options={
                'verbose_name': 'Case File',
                'verbose_name_plural': 'Case File',
            },
        ),
    ]
