# Generated by Django 2.1.5 on 2019-01-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_auto_20190121_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempfiles', to=settings.AUTH_USER_MODEL, verbose_name='Temp File'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casefiles', to='cases.Case', verbose_name='Case File'),
        ),
    ]
