# Generated by Django 2.1.7 on 2019-02-26 03:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/casefile/', location='/app/media/casefile'), upload_to='', verbose_name='Case File'),
        ),
        migrations.AlterField(
            model_name='tempfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/tempfile/', location='/app/media/tempfile'), upload_to='', verbose_name='Temp file'),
        ),
    ]
