version: '3.3'

volumes:
    postgres_data: {}
    portainer_data: {}

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /app/scripts/gunicorn.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    container_name: frontend
    build:
      context: .
      dockerfile: nginx/base.Dockerfile
    image: froggy-service-nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
