apiVersion: v1
kind: Service
metadata:
  name: {{ template "froggy-service.redis" . }}
  labels:
    app.kubernetes.io/name: {{ template "froggy-service.redis" . }}
    helm.sh/chart: {{ include "froggy-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ template "froggy-service.redis" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
