# Generated by Django 2.1.5 on 2019-01-06 00:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Arrange Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Arranged Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Time')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranges', to='cases.Case', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Arrange',
                'verbose_name_plural': 'Arrange',
                'ordering': ('id',),
            },
        ),
    ]
