# Generated by Django 2.1.5 on 2019-01-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('arranges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrange',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranges', to='cases.Case', verbose_name='Case'),
        ),
    ]
