# Generated by Django 2.1.5 on 2019-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arranges', '0002_arrange_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
