apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.default.name }}
  labels:
    app.kubernetes.io/name: {{ template "froggy-service.name" . }}
    helm.sh/chart: {{ include "froggy-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- (.Files.Glob (.Values.serviceAccount.default.localPath)).AsSecrets | nindent 2 }}

