apiVersion: v1
kind: Service
metadata:
  name: {{ template "froggy-service.frontend" . }}
  labels:
    app.kubernetes.io/name: {{ template "froggy-service.frontend" . }}
    helm.sh/chart: {{ include "froggy-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ template "froggy-service.frontend" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
