apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: froggytaipei/froggy-service-nginx:latest
        name: froggy-service-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl
            - api-service:8000/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
